POST    http://localhost:5000/api/users HTTP/1.1
content-type: application/json

{
  "name": "omar faruk",
  "email": "omar@gamil.com",
  "profile_image": "dfjk"
}
### 

PATCH     http://localhost:5000/api/users/omar@gamil.com HTTP/1.1
content-type: application/json

{
  "name": "omar faruk1",
  "email": "omar@gamil.com",
  "profile_image": "dfjk"
}
